server_name = "catircservices.org"
admin_email = "whitequark@whitequark.org"

[net.ipv6]
address = "2a01:4f8:c012:5b7::1"
gateway = "fe80::1"

[net.ipv4]
address = "5.75.226.159"
gateway = "172.31.1.1"

[dns]
servers = ["2620:fe::fe", "9.9.9.9"]

[ssh]
pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC3Cn89kCKoRHtTt9ailswSbnO/PeqA70HUcbhzL3mml"

[web]
banner = """
<title>catircservices.org</title>
<style>dt { font-weight: bold; }</style>
<h1>Catherine's IRC Services</h1>
<p>Please email <a href="mailto:admin@catircservices.org">admin@catircservices.org</a> if you have an inquiry related to this server or its services. The administrator of this server is Catherine "whitequark".</p>
<p>This server hosts the following services:</p>
<dl>
  <dt>Matrix↭IRC double puppeting bridge</dt>
  <dd>
    This bridge is present in IRC channels under the <tt>_catircservices</tt> nickname.
    Real-time metrics are <a href="/metrics/d/matrix-appservice-irc/">available</a>.
  </dd>
</dl>
"""

[matrix]
registration = false

[irc]
ipv6_prefix = "2a01:4f8:c012:5b7:0:1::"
bot_username = "_catircservices"

[metrics]
enable = true
