# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Click" = super.buildPythonPackage rec {
    pname = "Click";
    version = "7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl";
      sha256 = "04rbcbf5p4kdc7ghlsddxrnglsvk4rsmzphnlxyfdfcmcdg0cd93";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Deprecated" = super.buildPythonPackage rec {
    pname = "Deprecated";
    version = "1.2.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/cb/c1a39ee51e3042df8b284e22c9c440ffad1c25f451bddd4bf9a8dc17cd75/Deprecated-1.2.4-py2.py3-none-any.whl";
      sha256 = "1zx4hx7mjis9c76v74a303knsggyyw2qmdhis6sl5gqacdpbmzlb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wrapt"
    ];
  };
  "Flask" = super.buildPythonPackage rec {
    pname = "Flask";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl";
      sha256 = "019zni23v4g0flw2ngz9hqvwdcq5rdhli5bppkycqig3nx2bg050";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Click"
      self."Jinja2"
      self."Werkzeug"
      self."itsdangerous"
    ];
  };
  "Flask-Caching" = super.buildPythonPackage rec {
    pname = "Flask-Caching";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/c0/5dce9fe8372a7b57b60ec7650e1aeb1a2f861393b0c6e7e2dcb71d2f31ab/Flask_Caching-1.4.0-py2.py3-none-any.whl";
      sha256 = "09zj6hjm3z828wfyg9pjk2daya6iwdda0pwln27x86f5diy85zj4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
    ];
  };
  "Flask-Gravatar" = super.buildPythonPackage rec {
    pname = "Flask-Gravatar";
    version = "0.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/4a/b20260e8d383d0037f2791dd8a3f3ea729ca9f02d7638677a34a236a8702/Flask_Gravatar-0.5.0-py2.py3-none-any.whl";
      sha256 = "14gmwwjc0j0rnw86ar1k7adp4k3zis8qxixzwx2j7yffb2509glk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
    ];
  };
  "Flask-Mail" = super.buildPythonPackage rec {
    pname = "Flask-Mail";
    version = "0.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz";
      sha256 = "0hazjc351s3gfbhk975j8k65cg4gf31yq404yfy0gx0bjjdfpr92";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."blinker"
    ];
  };
  "Flask-SQLAlchemy" = super.buildPythonPackage rec {
    pname = "Flask-SQLAlchemy";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/85/fd40f11861d97cbaf4b0369288a293f2017dcea1fd52da2a652b2ceae15a/Flask_SQLAlchemy-2.5.0-py2.py3-none-any.whl";
      sha256 = "0hq4rk3ph7jlwl6lymbcq70gw3fg001nb9zf802qhhhw8nzm6l8d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."SQLAlchemy"
    ];
  };
  "Flask-WTF" = super.buildPythonPackage rec {
    pname = "Flask-WTF";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/b7/8e7f9d2c5b65cd5d1c533194ddccd33e6920ce2514bee25c0c50281d44e4/Flask-WTF-0.8.4.tar.gz";
      sha256 = "1khbwmlrcnk9f46f7kf531n06pkyfs6nc8fk273js9mj2igngg2y";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."WTForms"
    ];
  };
  "Flask-XML-RPC" = super.buildPythonPackage rec {
    pname = "Flask-XML-RPC";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d7/04/8ae1f839415f2f674565c973cf27c586c0380da2fa4738e50cdb8150d1aa/Flask-XML-RPC-0.1.2.tar.gz";
      sha256 = "1dwalj7pc5iid9l1k50q5mllirnn9f5s7jq54a66x48a4j179p2a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
    ];

    # XXX(bin): missing `__init__.py`. This is an ~awful fix, but it's acceptable for now.
    fixupPhase = ''
      touch $out/lib/python2.7/site-packages/flaskext/__init__.py
    '';
  };
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "2.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl";
      sha256 = "1gf34cvid4hk9jj8wy0y1qllcj4xjrm7cm0aqm3kk6mvp2hkbjbl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyGithub" = super.buildPythonPackage rec {
    pname = "PyGithub";
    version = "1.43.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/e9/2c630c3b181489f79c264194e7129798e36db94f2172a190aa0aaa8ac92c/PyGithub-1.43.3.tar.gz";
      sha256 = "1xlfa77c669pxa4rbi8dxykkn2qd2nkaqppigx0qhg8syqwh3nbh";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Deprecated"
      self."PyJWT"
      self."requests"
    ];
  };
  "PyJWT" = super.buildPythonPackage rec {
    pname = "PyJWT";
    version = "1.6.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/d1/3378cc8184a6524dc92993090ee8b4c03847c567e298305d6cf86987e005/PyJWT-1.6.4-py2.py3-none-any.whl";
      sha256 = "1332238z60gablr9fc5fjdba9k2mnxv2caychc948m9vyh7kic9h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyNaCl" = super.buildPythonPackage rec {
    pname = "PyNaCl";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz";
      sha256 = "0330wyvggm19xhmwmz9rrr97lzbv3siwfy50gmax3vvgs7nh0q8c";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
  };
  "SQLAlchemy" = super.buildPythonPackage rec {
    pname = "SQLAlchemy";
    version = "1.4.50";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/0a/dabe332c40afebb0a979d3e66b34570fce2f8611bae19b186f0c69f54643/SQLAlchemy-1.4.50.tar.gz";
      sha256 = "1gvxf1q4xykl08am697w4y5manvcn0cm4fs0145y28gw17sxv5rv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "Unidecode" = super.buildPythonPackage rec {
    pname = "Unidecode";
    version = "1.0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/ef/67085e30e8bbcdd76e2f0a4ad8151c13a2c5bce77c85f8cad6e1f16fb141/Unidecode-1.0.22-py2.py3-none-any.whl";
      sha256 = "10imjayxpbkhw4h4vmkn5q866l8w8p0rf2vikxwzbn7k54vrvx3j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "WTForms" = super.buildPythonPackage rec {
    pname = "WTForms";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/c8/dac5dce9908df1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65/WTForms-2.2.1-py2.py3-none-any.whl";
      sha256 = "1w96jq1bihb8n2rlky31clgmqb3drvllkgfdfw4cb0kmh8n0kvp3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Werkzeug" = super.buildPythonPackage rec {
    pname = "Werkzeug";
    version = "0.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl";
      sha256 = "16z4r61ia0905qx83f1qcnhczv8d9pfgvqhycnqqwmcka9rp7nnm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "amqp" = super.buildPythonPackage rec {
    pname = "amqp";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/90/bb5ce93521772f083cb2d7a413bb82eda5afc62b4192adb7ea4c7b4858b9/amqp-2.6.1-py2.py3-none-any.whl";
      sha256 = "0ndaq0j3901p6ihdc8jq2fwc1nh4ga82j4jc8waizjc7p0zk2zxa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."vine"
    ];
  };
  "bcrypt" = super.buildPythonPackage rec {
    pname = "bcrypt";
    version = "3.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/ec/bb6b384b5134fd881b91b6aa3a88ccddaad0103857760711a5ab8c799358/bcrypt-3.1.4.tar.gz";
      sha256 = "13cyrnqwkhc70rs6dg65z4yrrr3dc42fhk11804fqmci9hvimvb7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
  };
  "billiard" = super.buildPythonPackage rec {
    pname = "billiard";
    version = "3.6.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/91/40de1901da8ec9eeb7c6a22143ba5d55d8aaa790761ca31342cedcd5c793/billiard-3.6.4.0.tar.gz";
      sha256 = "0ismj2p8c66ykpss94rs0bfra5agxxmljz8r3gaq79r8valfb799";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "blinker" = super.buildPythonPackage rec {
    pname = "blinker";
    version = "1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz";
      sha256 = "1dpq0vb01p36jjwbhhd08ylvrnyvcc82yxx3mwjx6awrycjyw6j7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "celery" = super.buildPythonPackage rec {
    pname = "celery";
    version = "4.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/0c/609e3611d20c9f8d883852d1be5516671f630fb08c8c1e56911567dfba7b/celery-4.4.7-py2.py3-none-any.whl";
      sha256 = "0ifa7f4p46kx47asr7hrr0vx0dk2s6bkjah38yviyy2hwrb1sbm9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."billiard"
      self."kombu"
      self."pytz"
      self."vine"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2018.10.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl";
      sha256 = "0k2al0j1b71ibp9nnzbjaxaq2x2rj900fid5xnkjyzmh32aw179k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz";
      sha256 = "0x075521fxwv0mfp4cqzk7lvmw4n94bjw601qkcv314z5s182704";
    };
    format = "setuptools";
    doCheck = false;
    # XXX(bin): manually added
    buildInputs = [
      pkgs."libffi"
    ];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "3.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
      sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "configparser" = super.buildPythonPackage rec {
    pname = "configparser";
    version = "4.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl";
      sha256 = "0k7yqfkxal508c95c4rzl8cpzajs7n450245vvgla37ng6f1sk15";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "contextlib2" = super.buildPythonPackage rec {
    pname = "contextlib2";
    version = "0.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl";
      sha256 = "004wfr9xkr58s0xi3f9x0lhwzzgg9qpjbi8yr4pg8bwxcxp0l9pm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "3.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/85/38715448253404186029c575d559879912eb8a1c5d16ad9f25d35f7c4f4c/cryptography-3.3.2.tar.gz";
      sha256 = "1vcvw4lkw1spiq322pm1256kail8nck6bbgpdxx3pqa905wd6q2s";
    };
    format = "setuptools";
    doCheck = false;
    # XXX(bin): manually added
    buildInputs = [
      pkgs."openssl_1_1"
    ];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."enum34"
      self."ipaddress"
      self."six"
    ];
  };
  "docopt" = super.buildPythonPackage rec {
    pname = "docopt";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "enum34" = super.buildPythonPackage rec {
    pname = "enum34";
    version = "1.1.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl";
      sha256 = "0lwd0l4vjx4yii75k1l0bzrzp5pqn0rhmrw4n8yspwp3dlfj12m9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fabric" = super.buildPythonPackage rec {
    pname = "fabric";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/e4/e6fa248c94ee5d45def54b609fcf70f39d0b7f7050f2d4405c5f156b5516/fabric-2.4.0-py2.py3-none-any.whl";
      sha256 = "1xicgzkbkbvjbhi12xmcczz87bi4hk8j82wdg94m5kv37wpqylwq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."invoke"
      self."paramiko"
    ];
  };
  "gevent" = super.buildPythonPackage rec {
    pname = "gevent";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/92/b111f76e54d2be11375b47b213b56687214f258fd9dae703546d30b837be/gevent-1.2.2.tar.gz";
      sha256 = "0bbbjvi423y9k9xagrcsimnayaqymg6f2dj76m9z3mjpkjpci4a7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."greenlet"
    ];
  };
  "greenlet" = super.buildPythonPackage rec {
    pname = "greenlet";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/1e/632e55a04d732c8184201238d911207682b119c35cecbb9a573a6c566731/greenlet-2.0.2.tar.gz";
      sha256 = "1h1l1mll5s4y1b09asf2jps0m7wyshnis1aassz9gc3xmw9xrj77";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gunicorn" = super.buildPythonPackage rec {
    pname = "gunicorn";
    version = "19.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl";
      sha256 = "0w947i3p0b7y1qxkpfj573s6lvf7r52rynayvyjkcyqmni00p3ma";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "httplib2" = super.buildPythonPackage rec {
    pname = "httplib2";
    version = "0.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/ad/2371116b22d616c194aa25ec410c9c6c37f23599dcd590502b74db197584/httplib2-0.22.0.tar.gz";
      sha256 = "10fzh8yqzibyb6cv7z93hxhwirgfdrr8rplb90i87c2sxz2hp8fp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl";
      sha256 = "0vhq1rv706rd0d8km4ii4n6hqv6ma842w07va1lgrhaszca6hshm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "2.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/b4/877779cd7b5a15536ecbe0655cfb35a0de0ede6d888151fd7356d278c47d/importlib_metadata-2.1.3-py2.py3-none-any.whl";
      sha256 = "0gb9b9yv2kpzdj8ixjsjqfld323czd9x5kn4yal7xfpraq45mrjj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."configparser"
      self."contextlib2"
      self."pathlib2"
      self."zipp"
    ];
  };
  "invoke" = super.buildPythonPackage rec {
    pname = "invoke";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/32/6ed0bace971c5310d923e7c4abf475451ef20fa22c458138dd1aad664044/invoke-1.2.0-py2-none-any.whl";
      sha256 = "0bl98d5xvbiyi87rh9imrhf0318gpyciw7dj1wrl0nyjsii94vzb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipaddress" = super.buildPythonPackage rec {
    pname = "ipaddress";
    version = "1.0.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl";
      sha256 = "1k3zap9zjzgz21psvgfwf4xzjx7z5rm2f03v2fdbpdbcwqwll3vf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "itsdangerous" = super.buildPythonPackage rec {
    pname = "itsdangerous";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl";
      sha256 = "0jfp17fv977gv3lm78c4jyyrlpjw5qp65df8k3mkxckw0jr728mi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kombu" = super.buildPythonPackage rec {
    pname = "kombu";
    version = "4.6.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/34/3eea6a3a9ff81b0c7ddbdceb22a1ffc1b5907d863f27ca19a68777d2211d/kombu-4.6.11-py2.py3-none-any.whl";
      sha256 = "02hfbcjj9vlhb6gzx2fihdj4h24lyrrkslyn7bcr88aanpzwsj5y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
      self."importlib-metadata"
    ];
  };
  "oauth2" = super.buildPythonPackage rec {
    pname = "oauth2";
    version = "1.9.0.post1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/6f/86db603912ecd04109af952c38bc08928886cf0e34c723481fa7db98b4b5/oauth2-1.9.0.post1-py2.py3-none-any.whl";
      sha256 = "1rk669zjjlhv5b1x71jsyra65cd8h46ln8gi2cqxcvgl04iw9d8m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."httplib2"
    ];
  };
  "paramiko" = super.buildPythonPackage rec {
    pname = "paramiko";
    version = "2.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl";
      sha256 = "0fqzi9jlqjz80kbr7rbfgqg55h0ks6zms5a09jr11n60njzv45iw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyNaCl"
      self."bcrypt"
      self."cryptography"
      self."pyasn1"
    ];
  };
  "pathlib2" = super.buildPythonPackage rec {
    pname = "pathlib2";
    version = "2.3.7.post1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/eb/4af4bcd5b8731366b676192675221c5324394a580dfae469d498313b5c4a/pathlib2-2.3.7.post1-py2.py3-none-any.whl";
      sha256 = "0nyai5s5ffafvkxj34him8xcchs3k83jyy3x8srz2lh403ys0rjj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."scandir"
      self."six"
      self."typing"
    ];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl";
      sha256 = "0vicia5ims2zsqc96gkfi15afsvprhwgp7kkwa0br4xfr6l46sys";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl";
      sha256 = "12y8xwjb118a4jqvvfg9k90kqg03n4d3ygb5csz0l81wxy4pb7gg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2023.3.post1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl";
      sha256 = "1is6yqdr56vln3fbyl7bgh0437mascvqj7n12ik50s0vp0bdhhnf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "raven" = super.buildPythonPackage rec {
    pname = "raven";
    version = "6.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/3a/b3e46b279b8bdd9eb55857d0e95044cad31732c80f628bb75e1e9e881a32/raven-6.9.0-py2.py3-none-any.whl";
      sha256 = "0sp41hq25pg9jfqrm3w868kby5bcp76vxx0d8papdcf1l8z4zx4m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."contextlib2"
    ];
  };
  "redis" = super.buildPythonPackage rec {
    pname = "redis";
    version = "2.10.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/f6/7a76333cf0b9251ecf49efff635015171843d9b977e4ffcf59f9c4428052/redis-2.10.6-py2.py3-none-any.whl";
      sha256 = "1yrhygbgf9sg17gndb8rsbz9v459czlv6plbdv7lx950yalh06ca";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.20.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl";
      sha256 = "0m7zwf93jilav9s3wbd9dvsp4lkcjy09rf4xi34k77ijwhha3cv5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
  };
  "scandir" = super.buildPythonPackage rec {
    pname = "scandir";
    version = "1.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz";
      sha256 = "1bkqwmf056pkchf05ywbnf659wqlp6lljcdb0y88wr9f0vv32ijd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing" = super.buildPythonPackage rec {
    pname = "typing";
    version = "3.10.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/cb/da856e81731833b94da70a08712f658416266a5fb2a9d9e426c8061becef/typing-3.10.0.0-py2-none-any.whl";
      sha256 = "0253k09zw6pwqcrxlkj5p0y219kgqkgjl2b78lxl3gsz1kr9w8f7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.24.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl";
      sha256 = "0fgyaabjnn0bghf5xldnsa34l6xxljg0bpsgmppzphizvb52kgv1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "utopia" = super.buildPythonPackage rec {
    pname = "utopia";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/TkTech/utopia/archive/70293ed5e1ca55232e0fae71061e7e9b9b29be6f.tar.gz";
      sha256 = "0891r9byims8d682kd6c2qxikr16bry8r3n44nzv88wlna9jidvh";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."blinker"
      self."gevent"
    ];
  };
  "vine" = super.buildPythonPackage rec {
    pname = "vine";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl";
      sha256 = "1bwq7yx13npsnil8wlljhvvndnfs4pp47mf8jlh6zzfiav64fjga";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.10.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz";
      sha256 = "1ip3dwib39xhp79kblskgvz3fjzcwxgx3fs3ahdixhpjg7a61mfl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "xmltodict" = super.buildPythonPackage rec {
    pname = "xmltodict";
    version = "0.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/a9/7e99652c6bc619d19d58cdd8c47560730eb5825d43a7e25db2e1d776ceb7/xmltodict-0.11.0-py2.py3-none-any.whl";
      sha256 = "0596ygm4w1ya39kgcyj4z7aaz1yg8wkr29n5vsx13xlz1297vl5d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl";
      sha256 = "08gricb4820hrj9lxhsy6q6p16n5139zz7z04w6s70z4jwvydng0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."contextlib2"
    ];
  };
}
