serverName = "catircservices.org"
promptColor = "1;31"

[net.ipv6]
address = "2a01:4f8:c012:5b7::1"
gateway = "fe80::1"

[net.ipv4]
address = "5.75.226.159"
gateway = "172.31.1.1"

[dns]
servers = ["2620:fe::fe", "9.9.9.9"]

[ssh]
pubkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC3Cn89kCKoRHtTt9ailswSbnO/PeqA70HUcbhzL3mml whitequark",
]

[web]
acmeEmail = "admin@catircservices.org"
banner = """
<title>catircservices.org</title>
<style>dt { font-weight: bold; }</style>
<h1>Catherine's IRC Services (Production)</h1>
<p>Please email <a href="mailto:admin@catircservices.org">admin@catircservices.org</a> if you have an inquiry related to this server or its services. The administrator of this server is Catherine "whitequark".</p>
<p>This server hosts the following services:</p>
<dl>
  <dt>Matrix homeserver</dt>
  <dd>
    The homeserver is deployed solely to support the IRC bridge.
  </dd>
  <dt>Matrix↭IRC double puppeting bridge</dt>
  <dd>
    The bridge is present in certain <a href="https://libera.chat">libera.chat</a> IRC channels under the <tt>_catircservices</tt> nickname.
    Real-time metrics are <a href="/metrics/public-dashboards/dacd39605d844c9f91f3772b84b36837">available</a>.
  </dd>
</dl>
"""

[matrix]
registration = false

[irc]
ipv6Prefix = "2a01:4f8:c012:5b7:0:1::"
botUsername = "_catircservices"
botNickname = "_catircservices"

rooms = []
channels = []

[irc.mappings."#prjbureau"]
roomIds = ["!ksivXUJPtdDUjwEPLU:catircservices.org"]

[irc.mappings."#amaranth-lang"]
roomIds = ["!pYVedTwEYiMdCdysAu:catircservices.org"]

[irc.mappings."#glasgow"]
roomIds = ["!EDwUemPmPNSHXcaynd:catircservices.org"]

[irc.mappings."#riscv"]
roomIds = ["!TPJQRaBauCaUVymfox:catircservices.org"]

[irc.mappings."#litex"]
roomIds = ["!LhJjrGmNCUyJajtYYf:catircservices.org"]

[irc.mappings."#yosys"]
roomIds = ["!kYDVwycFCZBXLOyaMW:catircservices.org"]

[discord]
applicationId = "1135424862811324416"
selfServiceBridging = false
adminMxid = "@whitequark:matrix.org"

[metrics]
enable = true

[backup]
enable = true
