serverName = "staging.catircservices.org"
promptColor = "1;32"

[net.ipv6]
address = "2a01:4f8:c012:907c::1"
gateway = "fe80::1"

[net.ipv4]
address = "128.140.91.194"
gateway = "172.31.1.1"

[dns]
servers = ["2620:fe::fe", "9.9.9.9"]

[ssh]
pubkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC3Cn89kCKoRHtTt9ailswSbnO/PeqA70HUcbhzL3mml whitequark",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILF88y4TW1zG+36pPC48tNtHiMSWUBHM0X4aRwZApPoC bin",
]

[web]
acmeEmail = "admin@catircservices.org"
banner = """
<title>staging.catircservices.org</title>
<h1>Catherine's IRC Services (Staging)</h1>
<p>This server is a staging environment for <a href="https://catircservices.org">catircservices.org</a>.</p>
"""

[matrix]
registration = false

[irc]
ipv6Prefix = "2a01:4f8:c012:907c:0:1::"
botUsername = "_catircstaging"
botNickname = "_catircstaging"

rooms = []
channels = []

[irc.mappings."#catircservices-staging"]
roomIds = ["!EfLWKazQAwfGapdFJP:staging.catircservices.org"]

[discord]
applicationId = "1135426125452025937"
selfServiceBridging = false
adminMxid = "@whitequark:matrix.org"

[metrics]
enable = true

[backup]
enable = true
restic = true
tarsnap = false
